In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [10]:
all_labels = ["braunglas", "gruenglas", "weissglas", "keinglas"]

# Load the MNIST dataset
dataframes = []

# Loop through each CSV file in the directory
for filename in os.listdir("."):
    if filename.endswith('.csv'):
        # Extract the label from the filename (e.g., label1.csv -> label1)
        label = os.path.splitext(filename)[0]
        
        # Read the CSV file into a DataFrame
        df = pd.read_csv(filename, index_col=None)
        
        # Add a column for the label
        df['label'] = label
        
        # Append the DataFrame to the list
        dataframes.append(df)


# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)


combined_df = combined_df.sample(frac=1).reset_index(drop=False)

# Example: Separate features and labels
X = combined_df.drop(columns=['label', "index"]).values

# y is 4 one-hot encoded columns for the 3 classes and 1 for the no class
y = np.array([all_labels.index(v) for v in combined_df['label'].values])

y = to_categorical(y, num_classes=2)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


print(list(zip(x_train, y_train)))


[(array([0.09019608, 0.38431373, 0.17647059, 0.26757946, 0.76535234,
       0.20844889]), array([0., 1.])), (array([0.1372549 , 0.17647059, 0.16078431, 0.32431124, 0.74807843,
       0.18628906]), array([1., 0.])), (array([0.25490196, 0.28235294, 0.26666667, 0.31435999, 0.81633494,
       0.18057292]), array([1., 0.])), (array([0.30980392, 0.2627451 , 0.23921569, 0.24941262, 0.75845291,
       0.17911784]), array([1., 0.])), (array([0.30588235, 0.25098039, 0.25098039, 0.2832827 , 0.78475314,
       0.17674316]), array([1., 0.])), (array([0.31764706, 0.34509804, 0.34509804, 0.30665787, 0.80667975,
       0.18063639]), array([1., 0.])), (array([0.41960784, 0.45490196, 0.2745098 , 0.26152252, 0.71580386,
       0.23274577]), array([0., 1.])), (array([0.11764706, 0.45882353, 0.28627451, 0.26596437, 0.73852512,
       0.21783366]), array([0., 1.])), (array([0.20784314, 0.28627451, 0.31372549, 0.3482852 , 0.79757154,
       0.20687012]), array([1., 0.])), (array([0.29019608, 0.23137255, 0.18

In [11]:
model = Sequential()
model.add(Dense(x_train.shape[1], activation='relu', input_shape=(x_train.shape[1],)))
# model.add(Dense(1, activation='relu', input_shape=(1,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(2, activation='softmax'))

# Compile the model
model.compile(optimizer="nadam",
              loss='categorical_crossentropy',
              metrics=['accuracy'])



c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
for i in range(len(x_train)):
    print(x_train[i], y_train[i])

[0.09019608 0.38431373 0.17647059 0.26757946 0.76535234 0.20844889] [0. 1.]
[0.1372549  0.17647059 0.16078431 0.32431124 0.74807843 0.18628906] [1. 0.]
[0.25490196 0.28235294 0.26666667 0.31435999 0.81633494 0.18057292] [1. 0.]
[0.30980392 0.2627451  0.23921569 0.24941262 0.75845291 0.17911784] [1. 0.]
[0.30588235 0.25098039 0.25098039 0.2832827  0.78475314 0.17674316] [1. 0.]
[0.31764706 0.34509804 0.34509804 0.30665787 0.80667975 0.18063639] [1. 0.]
[0.41960784 0.45490196 0.2745098  0.26152252 0.71580386 0.23274577] [0. 1.]
[0.11764706 0.45882353 0.28627451 0.26596437 0.73852512 0.21783366] [0. 1.]
[0.20784314 0.28627451 0.31372549 0.3482852  0.79757154 0.20687012] [1. 0.]
[0.29019608 0.23137255 0.18823529 0.27455813 0.79593257 0.1768929 ] [1. 0.]
[0.4        0.46666667 0.45882353 0.32201165 0.75368026 0.20090658] [1. 0.]
[0.03137255 0.26666667 0.09803922 0.26503609 0.76568914 0.21554199] [0. 1.]
[0.10980392 0.44705882 0.20784314 0.24620496 0.71310567 0.22509603] [0. 1.]
[0.02745098 

In [13]:
# Train the model
model.fit(x_train, y_train, epochs=150, batch_size=32)

# Evaluate the model
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f'Test accuracy: {test_accuracy:.4f} and loss: {test_loss:.4f}')



Epoch 1/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4929 - loss: 0.6975
Epoch 2/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5502 - loss: 0.6901 
Epoch 3/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5255 - loss: 0.6914 
Epoch 4/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4734 - loss: 0.6968 
Epoch 5/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5185 - loss: 0.6906 
Epoch 6/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4860 - loss: 0.6941 
Epoch 7/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5420 - loss: 0.6867 
Epoch 8/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5090 - loss: 0.6903 
Epoch 9/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5177 - loss: 0.6886  
Epoch 10/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4873 - loss: 0.6919 
Epoch 11/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5680 - loss: 0.6827 
Epoch 12/150
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5094 - los

In [14]:
model.save('model.keras')