In [15]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [16]:
all_labels = ["braunglas", "gruenglas", "weissglas", "keinglas"]

# Load the MNIST dataset
dataframes = []

# Loop through each CSV file in the directory
for filename in os.listdir("."):
    if filename.endswith('.csv'):
        # Extract the label from the filename (e.g., label1.csv -> label1)
        label = os.path.splitext(filename)[0]
        
        # Read the CSV file into a DataFrame
        df = pd.read_csv(filename, index_col=None)
        
        # Add a column for the label
        df['label'] = label
        
        # Append the DataFrame to the list
        dataframes.append(df)


# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)


combined_df = combined_df.sample(frac=1).reset_index(drop=False)

# Example: Separate features and labels
X = combined_df.drop(columns=['label', "index"]).values

# y is 4 one-hot encoded columns for the 3 classes and 1 for the no class
y = np.array([all_labels.index(v) for v in combined_df['label'].values])

y = to_categorical(y, num_classes=3)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


print(list(zip(x_train, y_train)))


[(array([0.12156863, 0.12941176, 0.10980392, 0.30707283, 0.82485592,
       0.17937663]), array([1., 0., 0.])), (array([0.2745098 , 0.36862745, 0.21568627, 0.28375997, 0.63182301,
       0.23240885]), array([0., 1., 0.])), (array([0.25882353, 0.37254902, 0.19607843, 0.24537979, 0.7577035 ,
       0.22584473]), array([0., 1., 0.])), (array([0.64705882, 0.71764706, 0.69019608, 0.58166465, 0.7407726 ,
       0.03083659]), array([0., 0., 1.])), (array([0.37254902, 0.45098039, 0.30588235, 0.27104617, 0.69949024,
       0.24946777]), array([0., 1., 0.])), (array([0.85490196, 0.85882353, 0.80392157, 0.59730261, 0.79126972,
       0.04947754]), array([0., 0., 1.])), (array([0.72941176, 0.76470588, 0.73333333, 0.73354712, 0.81249508,
       0.05044108]), array([0., 0., 1.])), (array([0.38039216, 0.43921569, 0.29019608, 0.26791957, 0.66322748,
       0.24168294]), array([0., 1., 0.])), (array([0.2745098 , 0.30588235, 0.29019608, 0.32144178, 0.80572448,
       0.18308594]), array([1., 0., 0.])), 

In [17]:
model = Sequential()
model.add(Dense(x_train.shape[1], activation='relu', input_shape=(x_train.shape[1],)))
# model.add(Dense(1, activation='relu', input_shape=(1,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Compile the model
model.compile(optimizer="nadam",
              loss='categorical_crossentropy',
              metrics=['accuracy'])



c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
for i in range(len(x_train)):
    print(x_train[i], y_train[i])

[0.12156863 0.12941176 0.10980392 0.30707283 0.82485592 0.17937663] [1. 0. 0.]
[0.2745098  0.36862745 0.21568627 0.28375997 0.63182301 0.23240885] [0. 1. 0.]
[0.25882353 0.37254902 0.19607843 0.24537979 0.7577035  0.22584473] [0. 1. 0.]
[0.64705882 0.71764706 0.69019608 0.58166465 0.7407726  0.03083659] [0. 0. 1.]
[0.37254902 0.45098039 0.30588235 0.27104617 0.69949024 0.24946777] [0. 1. 0.]
[0.85490196 0.85882353 0.80392157 0.59730261 0.79126972 0.04947754] [0. 0. 1.]
[0.72941176 0.76470588 0.73333333 0.73354712 0.81249508 0.05044108] [0. 0. 1.]
[0.38039216 0.43921569 0.29019608 0.26791957 0.66322748 0.24168294] [0. 1. 0.]
[0.2745098  0.30588235 0.29019608 0.32144178 0.80572448 0.18308594] [1. 0. 0.]
[0.4        0.36862745 0.28235294 0.31604645 0.7570529  0.2168099 ] [1. 0. 0.]
[0.08627451 0.39607843 0.11764706 0.25118876 0.760552   0.15168457] [0. 1. 0.]
[0.09411765 0.39607843 0.16470588 0.26582891 0.82524337 0.19965007] [0. 1. 0.]
[0.0627451  0.26666667 0.1254902  0.26113547 0.65238

In [19]:
# Train the model
model.fit(x_train, y_train, epochs=150, batch_size=32)

# Evaluate the model
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f'Test accuracy: {test_accuracy:.4f} and loss: {test_loss:.4f}')



Epoch 1/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.3700 - loss: 1.0999
Epoch 2/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3338 - loss: 1.1132 
Epoch 3/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2882 - loss: 1.1142 
Epoch 4/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3170 - loss: 1.0876 
Epoch 5/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3289 - loss: 1.0641 
Epoch 6/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3751 - loss: 1.0289 
Epoch 7/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3078 - loss: 1.0345 
Epoch 8/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3662 - loss: 1.0157 
Epoch 9/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4836 - loss: 0.9869 
Epoch 10/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6167 - loss: 0.9725  
Epoch 11/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6145 - loss: 0.9687 
Epoch 12/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6943 - los

In [21]:
model.save('model.keras')