In [27]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [28]:
all_labels = ["braunglas", "gruenglas", "weissglas", "keinglas"]

# Load the MNIST dataset
dataframes = []

# Loop through each CSV file in the directory
for filename in os.listdir("."):
    if filename.endswith('.csv'):
        # Extract the label from the filename (e.g., label1.csv -> label1)
        label = os.path.splitext(filename)[0]
        
        # Read the CSV file into a DataFrame
        df = pd.read_csv(filename, index_col=None)
        
        # Add a column for the label
        df['label'] = label
        
        # Append the DataFrame to the list
        dataframes.append(df)


# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)


combined_df = combined_df.sample(frac=1).reset_index(drop=False)

# Example: Separate features and labels
X = combined_df.drop(columns=['label', "index"]).values

# y is 4 one-hot encoded columns for the 3 classes and 1 for the no class
y = np.array([all_labels.index(v) for v in combined_df['label'].values])

y = to_categorical(y, num_classes=4)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [29]:
model = Sequential()
model.add(Dense(x_train.shape[1], activation='relu', input_shape=(x_train.shape[1],)))
# model.add(Dense(1, activation='relu', input_shape=(1,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(4, activation='softmax'))

# Compile the model
model.compile(optimizer="nadam",
              loss='categorical_crossentropy',
              metrics=['accuracy'])



c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [30]:
for i in range(len(x_train)):
    print(x_train[i], y_train[i])

[0.09803922 0.41176471 0.16862745 0.25139505 0.77706186 0.16586426] [0. 1. 0. 0.]
[0.67058824 0.42745098 0.30980392 0.3950544  0.56969085 0.04040039] [0. 0. 1. 0.]
[0.08235294 0.1254902  0.09803922 0.60830447 0.82142652 0.06989746] [0. 0. 0. 1.]
[0.29019608 0.23137255 0.18823529 0.27455813 0.79593257 0.1768929 ] [1. 0. 0. 0.]
[0.91764706 0.90196078 0.82745098 0.60996545 0.77907827 0.04506836] [0. 0. 1. 0.]
[0.76078431 0.43529412 0.31764706 0.88281592 0.79919461 0.03359375] [0. 0. 1. 0.]
[0.29019608 0.36862745 0.29803922 0.32485402 0.787373   0.19778646] [1. 0. 0. 0.]
[0.04705882 0.24313725 0.09803922 0.2572529  0.71464819 0.21820964] [0. 1. 0. 0.]
[0.03137255 0.26666667 0.09803922 0.26503609 0.76568914 0.21554199] [0. 1. 0. 0.]
[0.23529412 0.21568627 0.22352941 0.67283071 0.90538392 0.10751139] [0. 0. 0. 1.]
[0.17254902 0.18039216 0.19215686 0.43250303 0.8586694  0.10763835] [0. 0. 0. 1.]
[0.37254902 0.45098039 0.30588235 0.27104617 0.69949024 0.24946777] [0. 1. 0. 0.]
[0.12156863 0.41

In [31]:
# Train the model
model.fit(x_train, y_train, epochs=150, batch_size=32)

# Evaluate the model
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f'Test accuracy: {test_accuracy:.4f} and loss: {test_loss:.4f}')



Epoch 1/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.3686 - loss: 1.4191
Epoch 2/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3735 - loss: 1.4120 
Epoch 3/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4263 - loss: 1.3974 
Epoch 4/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4041 - loss: 1.3910  
Epoch 5/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4179 - loss: 1.3843 
Epoch 6/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4817 - loss: 1.3619  
Epoch 7/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4216 - loss: 1.3671  
Epoch 8/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4656 - loss: 1.3519 
Epoch 9/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4279 - loss: 1.3428 
Epoch 10/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4691 - loss: 1.3261  
Epoch 11/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4413 - loss: 1.3163 
Epoch 12/150
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4518 - 

In [33]:
model.save('model_with_noglass.keras')